// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF1tJ-t2aXvfA8etDvkhSwakuhOL4ax_E',
    appId: '1:65182351227:web:40468cb776b3ee275dc7de',
    messagingSenderId: '65182351227',
    projectId: 'na-rota-b4fe9',
    authDomain: 'na-rota-b4fe9.firebaseapp.com',
    databaseURL: 'https://na-rota-b4fe9-default-rtdb.firebaseio.com',
    storageBucket: 'na-rota-b4fe9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrpqvQwtjLLlup0LADjDZtjbZyodbAyKc',
    appId: '1:65182351227:android:7eb65a17c0fb4c3e5dc7de',
    messagingSenderId: '65182351227',
    projectId: 'na-rota-b4fe9',
    databaseURL: 'https://na-rota-b4fe9-default-rtdb.firebaseio.com',
    storageBucket: 'na-rota-b4fe9.firebasestorage.app',
  );
}
